import Router from '@koa/router';
import login from './login';
import register from './register';
import editprofile from './user/editprofile';
import getfilminfo from './user/getfilminfo';
import gethotfilms from './user/gethotfilms';
import getmyorders from './user/getmyorders';
import getuserinfo from './user/getuserinfo';
import pay from './user/pay';
import refund from './user/refund';
import getstats from './admin/getstats';
import getfilms from './admin/getfilms';
import editfilm from './admin/editfilm';
import addfilm from './admin/addfilm';
import delfilm from './admin/delfilm';
import getarrangements from './admin/getarrangements';
import addarrangement from './admin/addarrangement';
import delarrangement from './admin/delarrangement';
import gethalls from './admin/gethalls';
import addhall from './admin/addhall';
import edithall from './admin/edithall';
import delhall from './admin/delhall';
import getorders from './admin/getorders';
import getusers from './admin/getusers';
import addadmin from './admin/addadmin';
import deluser from './admin/deluser';

const router = new Router();
router.post('/login', login);
router.post('/register', register);

router.get('/user/getuserinfo', getuserinfo);
router.get('/user/gethotfilms', gethotfilms);
router.post('/user/editprofile', editprofile);
router.get('/user/getfilminfo', getfilminfo);
router.post('/user/pay', pay);
router.get('/user/getmyorders', getmyorders);
router.get('/user/refund', refund);

router.get('/admin/getstats', getstats);
router.get('/admin/getfilms', getfilms);
router.post('/admin/editfilm', editfilm);
router.post('/admin/addfilm', addfilm);
router.get('/admin/delfilm', delfilm);
router.get('/admin/getarrangements', getarrangements);
router.post('/admin/addarrangement', addarrangement);
router.get('/admin/delarrangement', delarrangement);
router.get('/admin/gethalls', gethalls);
router.post('/admin/addhall', addhall);
router.post('/admin/edithall', edithall);
router.get('/admin.delhall', delhall);
router.get('/admin/getorders', getorders);
router.get('/admin/getusers', getusers);
router.post('/admin/addadmin', addadmin);
router.get('/admin/deluser', deluser);

export default router;
